name:                AdventOfCode
version:             0.1.0.0
github:              "AshleyYakeley/AdventOfCode"
license:             BSD3
author:              "Ashley Yakeley"
maintainer:          "ashley@semantic.org"
copyright:           "2021 Ashley Yakeley"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/AshleyYakeley/AdventOfCode#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  AdventOfCode-2021-01:
    source-dirs: app/2021/01
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  AdventOfCode-2021-02:
    source-dirs: app/2021/02
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transformers
