name:                AdventOfCode
version:             0.1.0.0
github:              "AshleyYakeley/AdventOfCode"
license:             BSD3
author:              "Ashley Yakeley"
maintainer:          "ashley@semantic.org"
copyright:           "2021 Ashley Yakeley"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/AshleyYakeley/AdventOfCode#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- array
- containers
- regex-tdfa

default-extensions:
- ScopedTypeVariables
- LambdaCase
- ViewPatterns

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wno-partial-type-signatures

library:
  source-dirs: lib
  exposed-modules:
  - Lib

executables:
  AdventOfCode-2021-01:
    source-dirs: app/2021/01
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-02:
    source-dirs: app/2021/02
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-03:
    source-dirs: app/2021/03
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-04:
    source-dirs: app/2021/04
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-05:
    source-dirs: app/2021/05
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-06:
    source-dirs: app/2021/06
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-07:
    source-dirs: app/2021/07
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-08:
    source-dirs: app/2021/08
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-09:
    source-dirs: app/2021/09
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-10:
    source-dirs: app/2021/10
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-11:
    source-dirs: app/2021/11
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-12:
    source-dirs: app/2021/12
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-13:
    source-dirs: app/2021/13
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-14:
    source-dirs: app/2021/14
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-15:
    source-dirs: app/2021/15
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-16:
    source-dirs: app/2021/16
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-17:
    source-dirs: app/2021/17
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-18:
    source-dirs: app/2021/18
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-19:
    source-dirs: app/2021/19
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-20:
    source-dirs: app/2021/20
    dependencies: AdventOfCode
    main: Main.hs
