name:                AdventOfCode
version:             0.1.0.0
github:              "AshleyYakeley/AdventOfCode"
license:             BSD3
author:              "Ashley Yakeley"
maintainer:          "ashley@semantic.org"
copyright:           "2021 Ashley Yakeley"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/AshleyYakeley/AdventOfCode#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- array
- containers

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wno-partial-type-signatures

library:
  source-dirs: lib
  exposed-modules:
  - Lib

executables:
  AdventOfCode-2021-01:
    source-dirs: app/2021/01
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-02:
    source-dirs: app/2021/02
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-03:
    source-dirs: app/2021/03
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-04:
    source-dirs: app/2021/04
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-05:
    source-dirs: app/2021/05
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-06:
    source-dirs: app/2021/06
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-07:
    source-dirs: app/2021/07
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-08:
    source-dirs: app/2021/08
    dependencies: AdventOfCode
    main: Main.hs
  AdventOfCode-2021-09:
    source-dirs: app/2021/09
    dependencies: AdventOfCode
    main: Main.hs
